version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:8.11.3
commands:
  restore_dependencies:
    steps:
      - restore_cache:
          name: Restore node_modules
          key: frontend-deps-{{ checksum "yarn.lock" }}
  save_dependencies:
    steps:
      - save_cache:
          name: Cache node_modules
          key: frontend-deps-{{ checksum "yarn.lock" }}
          paths: ~/workspace/node_modules
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - restore_dependencies
      - run:
          name: Install dependencies
          command: yarn install
      - save_dependencies
  check:
    executor: default
    steps:
      - checkout
      - restore_dependencies
      - run:
          name: Run lint
          command: yarn run lint
workflows:
  work:
    jobs:
      - setup
      - check:
          requires:
            - setup
